In [2]:
import os
import duckdb

duckdb_path = os.getenv("DUCKDB_PATH")
assert duckdb_path is not None, "Variable 'DUCKDB_PATH' must be defined"

con = duckdb.connect(duckdb_path)
con.sql("SELECT * FROM INFORMATION_SCHEMA.TABLES;").df()

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action,TABLE_COMMENT
0,legislative,main,deputados,BASE TABLE,None,None,None,None,None,YES,NO,None,None
1,legislative,main,proposicoesTemas,BASE TABLE,None,None,None,None,None,YES,NO,None,None
2,legislative,main,votacoesObjetos,BASE TABLE,None,None,None,None,None,YES,NO,None,None
3,legislative,main,votacoesVotos,BASE TABLE,None,None,None,None,None,YES,NO,None,None
4,legislative,main,deputies_propositions,VIEW,None,None,None,None,None,NO,NO,None,None

In [4]:
dp_view_list = con.sql("SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE table_name = 'deputies_propositions';")

def create_deputies_propositions_view():
    query = open("../queries/deputies_propositions.sql").read()
    con.execute(f"CREATE OR REPLACE VIEW deputies_propositions AS {query}")

if (not dp_view_list.shape[0] > 0):
    create_deputies_propositions_view()

dp_view = con.sql("SELECT * FROM deputies_propositions;")
dp_view.df()

          proposicao_id  deputado_id voto
0               2574728       204549  Sim
1               2574728        73579  Sim
2               2574728       220538  Sim
3               2574728       160559  Sim
4               2574728       204501  Sim
...                 ...          ...  ...
24428641         349282       160632  Sim
24428642         349282       220558  Não
24428643         349282       204517  Não
24428644         349282       220592  Sim
24428645         349282       220552  Não

[24428646 rows x 3 columns]

In [ ]:
con.sql("DROP VIEW IF EXISTS deputies;")